Ext.define('Issuetracker.issuetracker.shared.com.model.issuetrackerboundedcontext.issuetracker.FeatureCategoryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureCategoryCode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureCategoryName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureCategoryDesc",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});