Ext.define('Issuetracker.issuetracker.shared.com.model.issuetrackerboundedcontext.issuetracker.IssueWorkflowModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "issueId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "issueTitle",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "issueDescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stepsToReproduce",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "creatorcontactid",
          "reference": "CoreContacts",
          "defaultValue": ""
     }, {
          "name": "dateCreated",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "projectid",
          "reference": "CreateProject",
          "defaultValue": ""
     }, {
          "name": "moduleid",
          "reference": "ProjectModule",
          "defaultValue": ""
     }, {
          "name": "featureid",
          "reference": "ProjectFeature",
          "defaultValue": ""
     }, {
          "name": "browser",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "oS",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "IssueAssignment",
          "reference": "IssueAssignmentModel"
     }, {
          "name": "IssueHeaders",
          "reference": "IssueHeadersModel"
     }, {
          "name": "AddWatchers",
          "reference": "AddWatchersModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});