Ext.define('Testl.testl.shared.com.model.humanresourcecontext.payroll.EmployeeDeclartionModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empDecId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empid",
          "reference": "EmpInformation",
          "defaultValue": ""
     }, {
          "name": "hRA",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "eightyC",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "eightyD",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "eightyG",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "eightyE",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "year",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});