Ext.define('Testl.testl.shared.com.model.humanresourcecontext.payroll.PaySlipModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "salaryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empid",
          "reference": "EmpInformation",
          "defaultValue": ""
     }, {
          "name": "basic",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "hra",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "convenceAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "medicalAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "educationalAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "specailAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "tax",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "takeHome",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "year",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "month",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "lop",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});