DROP TABLE IF EXISTS `ast_OrderMain_T`;

CREATE TABLE `ast_OrderMain_T` ( `orderId` VARCHAR(256) NOT NULL, `orderDate` DATETIME NULL DEFAULT NULL, `grandTotal` DOUBLE(10,2) NULL DEFAULT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `userId` VARCHAR(64) NULL DEFAULT NULL, `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`orderId`));

