DROP TABLE IF EXISTS `ast_Item_M`;

CREATE TABLE `ast_Item_M` ( `itemId` VARCHAR(256) NOT NULL, `productId` VARCHAR(256) NOT NULL, `categoryId` VARCHAR(256) NOT NULL, `brandId` VARCHAR(256) NOT NULL, `itemName` VARCHAR(256) NOT NULL, `itemPrice` DOUBLE(10,2) NOT NULL, `itemStock` INT(10) NOT NULL, `itemIcon` TEXT NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`itemId`));

