DROP TABLE IF EXISTS `ast_CheckboxTest_M`;

CREATE TABLE `ast_CheckboxTest_M` ( `pk` VARCHAR(256) NOT NULL, `a1` TINYINT(1) NULL DEFAULT '0', `a2` TINYINT(1) NULL DEFAULT '1', `a3` TINYINT(1) NOT NULL DEFAULT '0', `a4` TINYINT(1) NOT NULL DEFAULT '1', `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATE NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATE NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`pk`));

