Ext.define('Testl.testl.shared.com.model.humanresourcecontext.backgroundcheck.WorkExperienceModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "workPk",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empid",
          "reference": "EmpInformation",
          "defaultValue": ""
     }, {
          "name": "previousCompany",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "duration",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "immediateSupervisor",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "supervisorContactNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "worknResponsibilities",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "jobTitle",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "reasonForLeaving",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "salaryPerAanum",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "DocumentList",
          "reference": "DocumentListModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});