




ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
ORACLE_SID=XE
PATH=$PATH:$ORACLE_HOME/bin:$ORACLE_SID
export ORACLE_HOME
export ORACLE_SID
export PATH
ART_DATA_PATH=/tmp/applifire/db/CZN1ZOYRTSHGV5T4HPENRA/6BE6DB6D-9D38-4A34-8DE5-68F3A79FF98C/art/data
AST_DATA_PATH=/tmp/applifire/db/CZN1ZOYRTSHGV5T4HPENRA/6BE6DB6D-9D38-4A34-8DE5-68F3A79FF98C/ast/data
DB_NAME=applifire
USER=root
PASSWORD=root
PORT=3308
HOST=localhost
MYSQL=/usr/bin
PROJECT_ID=CZN1ZOYRTSHGV5T4HPENRA
PROJECT_VERSION_ID=1



echo 'copy ART data from applifire starts....'
echo 'copy ART data from applifire ends....'

