Ext.define('Testproject1.testproject1.shared.com.model.sales.DistributorModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "distributorcode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "distributorname",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "regioncode",
          "reference": "SalesRegion",
          "defaultValue": ""
     }, {
          "name": "longitude",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "lattitude",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});