Ext.define('Testbp.testbp.shared.com.model.testbc.EmpQModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "countryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "countryName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "countryCode1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "countryCode2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "countryFlag",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "capital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "currencyCode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "currencyName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "currencySymbol",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "capitalLatitude",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "capitalLongitude",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "isoNumeric",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "createdBy",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "createdDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "updatedBy",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "updatedDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "activeStatus",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "txnAccessCode",
          "type": "int",
          "defaultValue": ""
     }]
});