Ext.define('Issuetracker.issuetracker.shared.com.model.issuetrackerboundedcontext.projectmanager.ProjectModuleModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "moduleId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "projectid",
          "reference": "CreateProject",
          "defaultValue": ""
     }, {
          "name": "moduleName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "moduleShortName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "moduleDescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "version",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "build",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateOfCreation",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "ModuleUserMapping",
          "reference": "ModuleUserMappingModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});