Ext.define('Issuetracker.issuetracker.shared.com.model.issuetrackerboundedcontext.projectmanager.ProjectAccessRightsModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "projectAccessCode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "projectAccessName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "projectAccessDesc",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});