Ext.define('Issuetracker.issuetracker.shared.com.model.issuetrackerboundedcontext.projectmanager.ProjectFeatureModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "moduleid",
          "reference": "ProjectModule",
          "defaultValue": ""
     }, {
          "name": "projectid",
          "reference": "CreateProject",
          "defaultValue": ""
     }, {
          "name": "featureName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureShortName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "featureDescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "version",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "build",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "dateOfCreation",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "FeatureUserMapping",
          "reference": "FeatureUserMappingModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});