Ext.define('Newol.newol.shared.com.model.defaultcontext.defaultdomain.TestUiModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "productId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "categoryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "brandId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemPrice",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemStock",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemIcon",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "Save",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "Reset",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "Button",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "Grid",
          "type": "auto",
          "defaultValue": ""
     }]
});