DROP TABLE IF EXISTS `ast_TestEntity_M`;

CREATE TABLE `ast_TestEntity_M` ( `testId` VARCHAR(256) NOT NULL, `tDate` VARCHAR(256) NOT NULL, `eType` VARCHAR(256) NOT NULL, `cardNo` VARCHAR(256) NOT NULL, `eTime` VARCHAR(256) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`testId`));

