Ext.define('Newol.newol.web.com.view.shoppingcontext.onlineshopping.ItemTemplate', {
     "xtype": "itemTemplate",
     "items": [{
          "xtype": "hiddenfield",
          "fieldLabel": "itemId",
          "bindable": "itemId",
          "margin": 5,
          "name": "itemId",
          "title": "itemId",
          "itemId": "gedmkhi"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Item",
          "margin": 5,
          "bindable": "itemName",
          "name": "itemName",
          "title": "Item",
          "itemId": "jgcnioi"
     }, {
          "xtype": "image",
          "name": "itemIcon",
          "height": 100,
          "width": 100,
          "border": true,
          "margin": 5,
          "bindable": "itemIcon",
          "itemId": "kedjdji",
          "bind": {
               "src": "{itemIcon}"
          }
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Product",
          "margin": 5,
          "bindable": "productName",
          "name": "productName",
          "title": "Product",
          "itemId": "fpfbiii"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Category",
          "margin": 5,
          "bindable": "categoryName",
          "name": "categoryName",
          "title": "Category",
          "itemId": "bhbadli"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Brand",
          "margin": 5,
          "bindable": "brandName",
          "name": "brandName",
          "title": "Brand",
          "itemId": "ccagedi"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Price",
          "margin": 5,
          "bindable": "itemPrice",
          "name": "itemPrice",
          "title": "Price",
          "itemId": "fihhgai"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "Quantity",
          "name": "itemQuantity",
          "margin": 5,
          "bindable": "itemQuantity",
          "title": "Quantity",
          "itemId": "diohjai"
     }, {
          "xtype": "button",
          "name": "addToCart",
          "pluginName": "geolocation",
          "isNativeWidget": true,
          "isNativeGeoBtn": true,
          "text": "Add To Cart",
          "margin": 5,
          "itemId": "gipfgai",
          "listeners": {
               "click": "onAddToCartClick"
          }
     }],
     "border": true,
     "autoScroll": true,
     "margin": 5,
     "isPartialUI": true,
     "itemId": "fkalhhi",
     "dockedItems": [],
     "extend": "Ext.form.Panel",
     "requires": ["Newol.newol.web.com.controller.shoppingcontext.onlineshopping.ItemTemplateController", "Newol.newol.shared.com.viewmodel.shoppingcontext.onlineshopping.ItemTemplateViewModel", "Newol.newol.shared.com.model.shoppingcontext.onlineshopping.ItemTemplateModel"],
     "viewModel": "ItemTemplateViewModel",
     "controller": "ItemTemplateController"
});