Ext.define('Testprolic.testprolic.shared.com.model.appinsight.health.TestAModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "tstid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "tnm",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "tno",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});