Ext.define('Testse.testse.shared.com.model.aaaboundedcontext.authentication.UserModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userAccessCode",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "useraccesslevelid",
          "reference": "UserAccessLevel",
          "defaultValue": ""
     }, {
          "name": "useraccessdomainid",
          "reference": "UserAccessDomain",
          "defaultValue": ""
     }, {
          "name": "multiFactorAuthEnabled",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "genTempOneTimePassword",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "allowMultipleLogin",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "isLocked",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "isDeleted",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "changePasswordNextLogin",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "passwordExpiryDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "passwordAlgo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "lastPasswordChangeDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "sessionTimeout",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "PassRecovery",
          "reference": "PassRecoveryModel"
     }, {
          "name": "UserData",
          "reference": "UserDataModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});